import {
  UsersRound,
  UserPlus,
  UserMinus,
  BriefcaseBusiness,
  Trophy,
  Clock4,
  Building2,
  DollarSign,
} from "lucide-react";

export const employeeData = [
  {
    id: 1,
    heading: "Current Employees",
    icon: UsersRound,
    total: 6941,
    improvePercent: 2.5,
    chartData: [
      { desktop: 6.5 },
      { desktop: 8.5 },
      { desktop: 7.5 },
      { desktop: 9.0 },
      { desktop: 9.5 },
      { desktop: 8.5 },
    ],
  },
  {
    id: 2,
    heading: "New Hires",
    icon: UserPlus,
    improvePercent: 4.8,
    total: 640,
    chartData: [
      { desktop: 2.0 },
      { desktop: 2.8 },
      { desktop: 3.5 },
      { desktop: 4.2 },
      { desktop: 3.9 },
      { desktop: 4.8 },
    ],
  },
  {
    id: 3,
    heading: "Resigned Employees",
    icon: UserMinus,
    improvePercent: -1.2,
    total: 580,
    chartData: [
      { desktop: 1.5 },
      { desktop: 1.2 },
      { desktop: 2.0 },
      { desktop: 1.8 },
      { desktop: 2.3 },
      { desktop: 1.6 },
    ],
  },
  {
    id: 4,
    heading: "Active Projects",
    icon: BriefcaseBusiness,
    total: -78,
    improvePercent: 3.1,
    chartData: [
      { desktop: 3.5 },
      { desktop: 4.0 },
      { desktop: 4.8 },
      { desktop: 5.5 },
      { desktop: 6.2 },
      { desktop: 6.0 },
    ],
  },
  {
    id: 5,
    heading: "Employee Recognition",
    icon: Trophy,
    improvePercent: 6.7,
    total: 6941,
    chartData: [
      { desktop: 1.5 },
      { desktop: 2.5 },
      { desktop: 3.5 },
      { desktop: 4.8 },
      { desktop: 5.0 },
      { desktop: 5.6 },
    ],
  },
  {
    id: 6,
    heading: "Avg Work Hours",
    icon: Clock4,
    total: 106,
    improvePercent: 1.9,
    chartData: [
      { desktop: 7.0 },
      { desktop: 6.8 },
      { desktop: 7.2 },
      { desktop: 7.5 },
      { desktop: 7.3 },
      { desktop: 7.6 },
    ],
  },
  {
    id: 7,
    heading: "Remote Employees",
    icon: Building2,
    total: 850,
    improvePercent: 3.9,
    chartData: [
      { desktop: 2.2 },
      { desktop: 2.5 },
      { desktop: 2.8 },
      { desktop: 3.1 },
      { desktop: 3.5 },
      { desktop: 3.8 },
    ],
  },
  {
    id: 8,
    heading: "Payroll Growth",
    icon: DollarSign,
    total: 640,
    improvePercent: 4.3,
    chartData: [
      { desktop: 5.5 },
      { desktop: 6.2 },
      { desktop: 6.8 },
      { desktop: 7.1 },
      { desktop: 7.6 },
      { desktop: 8.0 },
    ],
  },
];

export const jobOptions = [
  { value: "job-openings", label: "Job Openings" },
  { value: "new-hires", label: "New Hires" },
  { value: "applications", label: "Applications Received" },
  { value: "interview", label: "Interview Stage" },
  { value: "attendance", label: "Attendance Rate" },
  { value: "absenteeism", label: "Absenteeism Rate" },
  { value: "cash-flow", label: "Cash Flow Status" },
  { value: "current-balance", label: "Current Balance" },
];

export const timeOptions = [
  { value: "weekly", label: "Weekly" },
  { value: "monthly", label: "Monthly" },
  { value: "yearly", label: "Yearly" },
];
